### ISSUE TITLE
VS2019编译出错

### ISSUE THREAD

**Issue by shirenfeng** [dathlin/OpcUaHelper#11]
严重性	代码	说明	项目	文件	行	禁止显示状态
警告		未能找到引用的组件“System.Xml.ReaderWriter”。	OpcUaHelper			
警告		未能找到引用的组件“System.Threading.Tasks.Extensions”。	OpcUaHelper			
警告		未能找到引用的组件“System.Text.Encodings.Web”。	OpcUaHelper			
警告		未能找到引用的组件“System.Security.Cryptography.X509Certificates”。	OpcUaHelper			
警告		未能找到引用的组件“System.Security.Cryptography.Primitives”。	OpcUaHelper			
警告		未能找到引用的组件“System.Security.Cryptography.Encoding”。	OpcUaHelper			
警告		未能找到引用的组件“System.Security.Cryptography.Algorithms”。	OpcUaHelper			
警告		未能找到引用的组件“System.Runtime.InteropServices.RuntimeInformation”。	OpcUaHelper			
警告		未能找到引用的组件“System.Runtime.CompilerServices.Unsafe”。	OpcUaHelper			
警告		未能找到引用的组件“System.Reflection.Metadata”。	OpcUaHelper			
警告		未能找到引用的组件“System.Numerics.Vectors”。	OpcUaHelper			
警告		未能找到引用的组件“System.Net.Sockets”。	OpcUaHelper			
警告		未能找到引用的组件“System.Net.Http”。	OpcUaHelper			
警告		未能找到引用的组件“System.IO.FileSystem”。	OpcUaHelper			
警告		未能找到引用的组件“System.IO.FileSystem.Primitives”。	OpcUaHelper			
警告		未能找到引用的组件“System.IO.Compression”。	OpcUaHelper			
警告		未能找到引用的组件“System.IO.Compression.ZipFile”。	OpcUaHelper			
警告		未能找到引用的组件“System.Globalization.Calendars”。	OpcUaHelper			
警告		未能找到引用的组件“System.Diagnostics.DiagnosticSource”。	OpcUaHelper			
警告		未能找到引用的组件“System.Console”。	OpcUaHelper			
警告		未能找到引用的组件“System.Collections.Immutable”。	OpcUaHelper			
警告		未能找到引用的组件“System.Buffers”。	OpcUaHelper			
警告		未能找到引用的组件“Opc.Ua.Server”。	OpcUaHelper			
警告		未能找到引用的组件“Opc.Ua.Gds.Server.Common”。	OpcUaHelper			
警告		未能找到引用的组件“Opc.Ua.Gds.Client.Common”。	OpcUaHelper			
警告		未能找到引用的组件“Opc.Ua.Core”。	OpcUaHelper			
警告		未能找到引用的组件“Opc.Ua.Configuration”。	OpcUaHelper			
警告		未能找到引用的组件“Opc.Ua.Client”。	OpcUaHelper			
警告		未能找到引用的组件“Newtonsoft.Json”。	OpcUaHelper			
警告		未能找到引用的组件“Microsoft.Win32.Primitives”。	OpcUaHelper			
警告		未能找到引用的组件“Microsoft.Net.Http.Headers”。	OpcUaHelper			
警告		未能找到引用的组件“Microsoft.Extensions.Primitives”。	OpcUaHelper			
警告		未能找到引用的组件“Microsoft.Extensions.PlatformAbstractions”。	OpcUaHelper			
警告		未能找到引用的组件“Microsoft.Extensions.Options”。	OpcUaHelper			
警告		未能找到引用的组件“Microsoft.Extensions.ObjectPool”。	OpcUaHelper			
警告		未能找到引用的组件“Microsoft.Extensions.Logging”。	OpcUaHelper			
警告		未能找到引用的组件“Microsoft.Extensions.Logging.Abstractions”。	OpcUaHelper			
警告		未能找到引用的组件“Microsoft.Extensions.FileSystemGlobbing”。	OpcUaHelper			
警告		未能找到引用的组件“Microsoft.Extensions.FileProviders.Physical”。	OpcUaHelper			
警告		未能找到引用的组件“Microsoft.Extensions.FileProviders.Abstractions”。	OpcUaHelper			
警告		未能找到引用的组件“Microsoft.Extensions.DependencyInjection”。	OpcUaHelper			
警告		未能找到引用的组件“Microsoft.Extensions.DependencyInjection.Abstractions”。	OpcUaHelper			
警告		未能找到引用的组件“Microsoft.Extensions.Configuration”。	OpcUaHelper			
警告		未能找到引用的组件“Microsoft.Extensions.Configuration.EnvironmentVariables”。	OpcUaHelper			
警告		未能找到引用的组件“Microsoft.Extensions.Configuration.Abstractions”。	OpcUaHelper			
警告		未能找到引用的组件“Microsoft.AspNetCore.WebUtilities”。	OpcUaHelper			
警告		未能找到引用的组件“Microsoft.AspNetCore.Server.Kestrel”。	OpcUaHelper			
警告		未能找到引用的组件“Microsoft.AspNetCore.Server.Kestrel.Https”。	OpcUaHelper			
警告		未能找到引用的组件“Microsoft.AspNetCore.Http”。	OpcUaHelper			
警告		未能找到引用的组件“Microsoft.AspNetCore.Http.Features”。	OpcUaHelper			
警告		未能找到引用的组件“Microsoft.AspNetCore.Http.Extensions”。	OpcUaHelper			
警告		未能找到引用的组件“Microsoft.AspNetCore.Http.Abstractions”。	OpcUaHelper			
警告		未能找到引用的组件“Microsoft.AspNetCore.Hosting”。	OpcUaHelper			
警告		未能找到引用的组件“Microsoft.AspNetCore.Hosting.Server.Abstractions”。	OpcUaHelper			
警告		未能找到引用的组件“Microsoft.AspNetCore.Hosting.Abstractions”。	OpcUaHelper			
警告		未能找到引用的组件“BouncyCastle.Crypto”。	OpcUaHelper

**Comment by shirenfeng** [comment]
请问，工程环境中要如何配置呢

**Comment by shirenfeng** [comment]
还有这个错误：
严重性	代码	说明	项目	文件	行	禁止显示状态
错误		无法处理文件 Forms\FormBrowseServer.resx，因为它位于 Internet 或受限区域中，或者文件上具有 Web 标记。要想处理这些文件，请删除 Web 标记。	OpcUaHelper

**Comment by dathlin** [comment]
啥情况。我这编译没有问题啊
